# These are supported funding model platforms

github: inspirationlinks
custom: https://www.paypal.com/donate/?hosted_button_id=B3EDBYK3LXSNS
#custom: ["https://www.paypal.com/donate/?hosted_button_id=B3EDBYK3LXSNS", Paypal]

#ko_fi: inspirationlinks
#buy_me_a_coffee: inspirationlinks
